name: Check Semantic PR
on:
  workflow_call:

jobs:
  semantic-pr:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          types: |
            feat
            fix
            refactor
            chore
            security
            revert
          scopes: |
            reqs
            docs
            tests
            build
            ci
            conf
            api
            core
            deps
            release
            github-actions
